
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: container
        image: hello-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 60
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        ports:
        - containerPort: 80
      restartPolicy: Always